preset: symfony

risky: true

enabled:
  - declare_strict_types

disabled:
  - phpdoc_summary

finder:
  not-path:
    - "tests/factories"
    - "tests/Model"
  not-name:
    - "bootstrap.php"
    - "cli-config.php"
