language: php

php:
  - '7.1'
  - '7.2'

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer

env:
  - SYMFONY_VERSION="3.*"
  - SYMFONY_VERSION="4.*"

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

before_script:
  - mysql -e 'CREATE DATABASE test;'
  - vendor/bin/doctrine orm:schema-tool:drop --force
  - vendor/bin/doctrine orm:schema-tool:create
